4.3b: 2D Numpy in Python

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
arr.size

12

In [7]:
arr[0][0:2]

array([1, 2])

In [8]:
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

np.dot(arr, B)

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])